<?php
/**
 * CORS Fix Script
 * Career Path Institute - Shimla
 * 
 * This script will fix CORS issues by updating all API endpoints
 */

echo "🔧 CORS FIX SCRIPT STARTING...\n\n";

// Get all PHP files in the api directory
function getAllPhpFiles($dir) {
    $files = [];
    $iterator = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($dir)
    );
    
    foreach ($iterator as $file) {
        if ($file->isFile() && $file->getExtension() === 'php') {
            $files[] = $file->getPathname();
        }
    }
    
    return $files;
}

$apiDir = __DIR__ . '/api';
$files = getAllPhpFiles($apiDir);

$corsHeaders = '
// CORS Headers - Auto-generated by fix-cors.php
header("Access-Control-Allow-Origin: http://localhost:5173");
header("Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS");
header("Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With, X-CSRF-Token");
header("Access-Control-Allow-Credentials: true");
header("Content-Type: application/json");

// Handle preflight OPTIONS request
if ($_SERVER[\'REQUEST_METHOD\'] === \'OPTIONS\') {
    http_response_code(200);
    exit();
}
';

$fixedCount = 0;
$skippedCount = 0;

foreach ($files as $file) {
    $content = file_get_contents($file);
    
    // Skip if already has CORS headers
    if (strpos($content, 'Access-Control-Allow-Origin') !== false) {
        echo "⏭️  Skipped (already has CORS): " . basename($file) . "\n";
        $skippedCount++;
        continue;
    }
    
    // Find the first <?php tag and add CORS headers after it
    $pattern = '/(<\?php\s*)/';
    if (preg_match($pattern, $content)) {
        $newContent = preg_replace($pattern, '$1' . $corsHeaders, $content, 1);
        
        if (file_put_contents($file, $newContent)) {
            echo "✅ Fixed: " . basename($file) . "\n";
            $fixedCount++;
        } else {
            echo "❌ Failed to fix: " . basename($file) . "\n";
        }
    } else {
        echo "⚠️  No PHP opening tag found: " . basename($file) . "\n";
        $skippedCount++;
    }
}

echo "\n" . str_repeat("=", 50) . "\n";
echo "🎉 CORS FIX COMPLETED!\n";
echo "✅ Fixed files: $fixedCount\n";
echo "⏭️  Skipped files: $skippedCount\n";
echo "📁 Total files processed: " . count($files) . "\n";
echo "\n🔍 Next steps:\n";
echo "1. Test the API endpoints in your browser\n";
echo "2. Check the CORS test page: http://localhost:5173/cors-test\n";
echo "3. Verify that data is loading in your React app\n";
echo str_repeat("=", 50) . "\n";
?>